### ISSUE TITLE
Sticky row/column

### ISSUE THREAD

**Issue by animtam111** [dragonwocky/notion-enhancer#124]
This feature might be one of the most requested in Notion twitter. It would be a lot easier if you could add feature like freeze row or column or both. Please include this if it's possible from your side.

**Comment by dragonwocky** [comment]
please provide a mockup/drawing example

**Comment by animtam111** [comment]
I don't know how to create mockups but you can take Google sheet as an example where we can stick row from view>freeze.

**Comment by dragonwocky** [comment]
google sheets has a very different ui/layout to notion.

literally just sketch a picture of what you want and take a photo of it.

**Comment by dragonwocky** [comment]
to make the first row of a table/list stick to the top of a page after scrolling you can do:
```css
.notion-collection_view_page-block
  .notion-page-block.notion-collection-item:nth-child(2) {
  background: var(--theme--main);
  z-index: 10;
  position: sticky;
  top: 0;
}
.notion-table-view
  .notion-collection_view_page-block
  .notion-page-block.notion-collection-item:nth-child(2) {
  top: 32px;
}
```

to do it specifically for a certain item replace `:nth-child(2)` with `[data-block-id="BLOCK_ID_HERE"]` (use the devtools inspector openable with ctrl+shift+i to find the block id)
