### ISSUE TITLE
Wrap database entries title in gallery, list and calendar views

### ISSUE THREAD

**Issue by fabiosangregorio** [dragonwocky/notion-enhancer#170]
Hi :)

**problem**
I always get frustrated when I can't view the full title of my tasks because it doesn't wrap in the database views. An example of this can be found in the screenshots below:
![](https://i.ibb.co/Cs5ykTr/1.png)
![](https://i.ibb.co/BtFfVRH/2.png)

**solution**
It would be great if an option could be added to wrap text on the gallery, calendar and list views, just like the table view does by default.

**Comment by fabiosangregorio** [comment]
Hi @dragonwocky , just wanted to let you know that I got part of this working with some CSS tweaks :)

Here you can see the version without the tweak:

![](https://i.imgur.com/IoK9iWO.png)

Here's the version with the tweak:

![](https://i.imgur.com/cgtJMsD.png)

As you can see table, board and gallery views work perfectly, while list and calendar have some problems.

I'll leave the CSS code here if it can be of use to you:
```css
/* Wrap everything */
.notion-collection-item [style*="white-space: nowrap"] {
  white-space: normal !important;
}
.notion-collection-item [style*="align-items: center; height: 20px"] {
  height: auto !important;
  align-items: flex-start !important;
}
.notion-collection-item [style*="overflow: hidden; width: 100%;"] {
  overflow: visible !important;
}
.notion-collection-item > a {
  overflow: visible !important;
  height: auto !important;
  min-height: 30px;
}

/* Don't wrap on table rows */
.notion-table-view .notion-collection-item [style*="white-space: nowrap"] {
  white-space: nowrap !important;
}
```
