### ISSUE TITLE
Hide the +new button on gallery view

### ISSUE THREAD

**Issue by monagarcia** [dragonwocky/notion-enhancer#22]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**problem**
Similar to the new button on the table and board view, the new button on the gallery view seems unnecessary and takes up too much space.

**solution**
Hide the new button on the gallery view

**alternatives (optional)**
have you tried to do this yourself? have you seen it done somewhere else? - Can't seem to find a solution for this.
would a different feature remove the need for this? - I don't think so.

**Comment by dragonwocky** [comment]
This one?

![image](https://user-images.githubusercontent.com/16874139/87514963-6f343600-c6be-11ea-975d-b1d7731b8edb.png)

This css should remove it:

```css
.notion-gallery-view .notion-selectable.notion-collection_view-block > [role="button"] {
  display: none !important;
}
```

I'll add this to the styling options in the next update of the enhancer, too.
