### ISSUE TITLE
Hide "Hidden Columns" and "Add a group" 

### ISSUE THREAD

**Issue by patsok** [dragonwocky/notion-enhancer#32]
Hi, i tried to hide "add a group" and "hidden columns" for all the board views in Notion but my code doesn't work 😕 

```
.notion-board-view>div:nth-child(1)>div:nth-child(4),
.notion-board-view>div:nth-child(1)>div:nth-child(1)>div:nth-child(3) {
        display: none !important;
}
```

```
.notion-board-view>div:nth-child(1)>div:nth-child(3),
.notion-board-view>div:nth-child(1)>div:nth-child(1)>div:nth-child(2){
    display: none !important;
}
```

Could you help me why this doesn't work? 
Developer tools are displaying that selectors are correct but there is no change to any of attributes.

I know that you post solution in the styling.md but still I want to know what is wrong with that.

**Comment by dragonwocky** [comment]
@patsok hmm, I just tested those and they worked... try this:
```css
.notion-board-view > [data-block-id] > div:nth-last-child(2),
.notion-board-view > [data-block-id] > div:first-child > div:nth-last-child(2) {
  display: none !important;
}

.notion-board-view > [data-block-id] > div:last-child,
.notion-board-view > [data-block-id] > div:first-child > div:last-child {
  display: none !important;
}
```

screenshots of the board + the devtools would be helpful.
