### ISSUE TITLE
Change in-line code font color

### ISSUE THREAD

**Issue by svpaz7** [dragonwocky/notion-enhancer#34]
Is it possible to add in this enhancer a way to change the in-line code font color?

The current in-line code font color is red, which is hard to read when using the dark theme. I've searched for a way to do so, but apparently, Notion doesn't have an option to change this.

It would be nice if we could change it through this enhancer, so that it would be more readable.

**Comment by dragonwocky** [comment]
yep, this is already one of the themeable options in the update (~70% done).
for now (these are the defaults):
```css
.notion-dark-theme [style*='color:#EB5757'] {
  color: #EB5757 !important;
  background: rgb(63, 68, 71) !important;
}
```
