### ISSUE TITLE
Hiding the comments on pages is also making the divider invisible

### ISSUE THREAD

**Issue by Crimson723** [dragonwocky/notion-enhancer#97]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
When hiding the discussion/comments on any notion page it is also making the dividers invisible.
Also if I remove the discussion hide styling from custom.css the dividers are showing again.

**expected behaviour**
The dividers should be visible even if the discussion is hidden.
**screenshots**
![Notion_T0vaoUIB6u](https://user-images.githubusercontent.com/70386364/92858965-80789500-f418-11ea-97b3-5e1dc7d24664.png)
**The blue highlighted area is where the divider should be.**

**platform**
Windows 10

**Comment by dragonwocky** [comment]
@Crimson723 which dividers are missing?

**Comment by Crimson723** [comment]
Yes. The divider that is added with three - or by /divider.

**Comment by dragonwocky** [comment]
use this:
```css
[style*='env(safe-area-inset-left)']:not(.notion-page-content)
  [style*='width: 100%; height: 1px;'],
.notion-page-view-discussion {
  display: none !important;
}
```
